[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pulami-k8s-airbyte-deployment"
version = "0.1.0"

dependencies = [
    "pulumi>=3.120.0",
    "pulumi-kubernetes>=4.9.0",
    "pulumi-aws>=6.0.0",

]